### ISSUE TITLE
WARN log about aotCompile, warnOnReflection always put out. is it intentended?

### ISSUE THREAD

**Issue by yokotaso** [nebula-plugins/nebula-clojure-plugin#12]
When I setting at gradle, `clojure.aotCompile = true`, and then I run gradle build task.
I got log like bellow:

```
'aotCompile' is deprecated and will go away in a future version. Please use 'clojure.aotCompile' instead.
'warnOnReflection' is deprecated and will go away in a future version. Please use 'clojure.warnOnReflection' instead.
```

I use `clojure.atoCompile` option. But WARN log is always put. 
above WARN log always seem to be put.

Is it intended log?

**Comment by sghill** [comment]
Fixed by #18 through removing the log.

This was in the original plugin and we don't currently have any plans of removing the property, so it seems fair to remove the log statements.
