### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by camechis** [nebula-plugins/nebula-clojure-plugin#2]
I noticed this plugin is just a basic wrapper on the Clojuresque plugin which doesn't look to be maintained anymore.  I would love to start using gradle to build my clojure projects and was wondering if there are any limitations of using this plugin vs leiningen?

**Comment by rspieldenner** [comment]
We haven't been doing much clojure work yet. Made the wrapper on clojuresque so it would work with our publishing code.

My quick thinking would just be the community default would mean plugins for things like ring might need to be written for gradle

**Comment by camechis** [comment]
Thanks,  I wish a well maintained plugin for clojure would call me along.

**Comment by uglyog** [comment]
This plugin is working well for me, there are a few issues that a line or two of build config overcomes. Apart from that, I have a project working with some Clojure alongside Java, Groovy and Scala code.
