### ISSUE TITLE
Gradle 2.12, nebula-clojure-plugin and clojuresque

### ISSUE THREAD

**Issue by rkapsi** [nebula-plugins/nebula-clojure-plugin#3]
Gradle 2.12 breaks unfortunately the nebula-clojure-plugin because clojuresque is using some internal API.

https://bitbucket.org/clojuresque/clojuresque/issues/4/plugin-stops-working-in-gradle-212

**Comment by rpalcolea** [comment]
Closing this since the plugin supports Gradle 5.6.2
